// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type IlovecatsDocumentDataSlicesSlice = never;

/**
 * Content for iLoveCats documents
 */
interface IlovecatsDocumentData {
  /**
   * Slice Zone field in *iLoveCats*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ilovecats.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IlovecatsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *iLoveCats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ilovecats.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *iLoveCats*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ilovecats.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *iLoveCats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ilovecats.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * iLoveCats document from Prismic
 *
 * - **API ID**: `ilovecats`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IlovecatsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IlovecatsDocumentData>,
    "ilovecats",
    Lang
  >;

export type AllDocumentTypes = IlovecatsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      IlovecatsDocument,
      IlovecatsDocumentData,
      IlovecatsDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
